/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestorplaylist;
//IMPORTACIONES
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Color;
import java.awt.Component;
/**
 *
 * @author jv134
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

   private PlaylistManager manager = new PlaylistManager(50); // arreglo de 50 canciones
        private boolean estaOrdenado = false;
        private int criterioOrden = PlaylistManager.ORDENAR_POR_NOMBRE;
 
// Modelo de la JTable (se declara aqui para poder actualizarlo)
        private DefaultTableModel modeloTabla;
     public Main() {
        
        initComponents();
        inicializar();
    }
     private void inicializar() {
    // Configurar columnas de la JTable
    modeloTabla = new DefaultTableModel(
        new String[]{"#", "Nombre", "Artista", "Álbum"}, 0) {
        @Override
        public boolean isCellEditable(int row, int col) { return false; }
    };
    jTable1.setModel(modeloTabla);
    jTable1.setRowHeight(24);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
 
    // Canciones de ejemplo precargadas (es necesario ponerlas aqui porque trabajaremos con un array :D )
    manager.agregar("Blinding Lights",   "The Weeknd",        "After Hours");
    manager.agregar("Shape of You",      "Ed Sheeran",        "Divide");
    manager.agregar("Bohemian Rhapsody", "Queen",             "A Night at the Opera");
    manager.agregar("Lose Yourself",     "Eminem",            "8 Mile");
    manager.agregar("Hotel California",  "Eagles",            "Hell Freezes Over");
    manager.agregar("Smells Like Teen",  "Nirvana",           "Nevermind");
    manager.agregar("Rolling in the Deep","Adele",            "21");
    manager.agregar("Uptown Funk",       "Bruno Mars",        "Uptown Special");
    manager.agregar("Bad Guy",           "Billie Eilish",     "When We All Fall Asleep");
    manager.agregar("Despacito",         "Luis Fonsi",        "Vida");
 
    actualizarTabla(-1);
    setStatus("✔ Playlist cargada con " + manager.getTamanio() + " canciones.", new Color(125, 211, 168));
}
private void actualizarTabla(int filaResaltada) {
    modeloTabla.setRowCount(0); // limpiar filas
    Cancion[] canciones = manager.getPlaylist();
    for (int i = 0; i < canciones.length; i++) {
        modeloTabla.addRow(new Object[]{
            i + 1,
            canciones[i].nombre,
            canciones[i].artista,
            canciones[i].album
        });
    }
 
    // Resaltar fila encontrada en búsqueda
    if (filaResaltada >= 0) {
        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable t, Object v,
                boolean sel, boolean foc, int row, int col) {
                super.getTableCellRendererComponent(t, v, sel, foc, row, col);
                if (row == filaResaltada) {
                    setBackground(new Color(5, 150, 105));
                    setForeground(Color.WHITE);
                } else {
                    setBackground(row % 2 == 0 ? new Color(30, 30, 40) : new Color(22, 22, 32));
                    setForeground(new Color(232, 230, 223));
                }
                return this;
            }
        });
        jTable1.repaint();
        jTable1.scrollRectToVisible(jTable1.getCellRect(filaResaltada, 0, true));
    } else {
        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable t, Object v,
                boolean sel, boolean foc, int row, int col) {
                super.getTableCellRendererComponent(t, v, sel, foc, row, col);
                setBackground(row % 2 == 0 ? new Color(30, 30, 40) : new Color(22, 22, 32));
                setForeground(new Color(232, 230, 223));
                return this;
            }
        });
        jTable1.repaint();
    }
}
 
private void setStatus(String msg, Color color) {
    jLabel1.setText(msg);
    jLabel1.setForeground(color);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Encontrada en:");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnOrdenar.setText("QuickSort");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton1.setText("Mostrar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("QuickSort");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Buscar ");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("QUE ES UNA PLAYLIST?");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "ARTISTA", "ALBUM"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("STATUS");

        jTextField1.setText("Buscar cancion o artista...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Nombre", "Por Artista" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton7.setText("Buscar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMostrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnOrdenar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnOrdenar)
                    .addComponent(btnBuscar)
                    .addComponent(btnAgregar)
                    .addComponent(btnSalir))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
      if (manager.estaVacia()) {
        setStatus("La playlist está vacia.", Color.YELLOW);
        return;
    }
    actualizarTabla(-1);
    setStatus("Mostrando " + manager.getTamanio() + " canciones.", new Color(96, 165, 250));
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
     if (manager.estaVacia()) {
        setStatus("La playlist está vacía.", Color.YELLOW);
        return;
    }
 
    // Mostrar estado ANTES
    String[] opciones = {"Por Nombre", "Por Artista"};
    int eleccion = JOptionPane.showOptionDialog(this,
        "¿Por que campo ordenar?\n\nEstado actual (antes del ordenamiento):\n" + obtenerEstadoResumido(),
        "QuickSort — Elegir criterio",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null, opciones, opciones[0]);
 
    if (eleccion == JOptionPane.CLOSED_OPTION) return;
 
    criterioOrden = (eleccion == 1)
        ? PlaylistManager.ORDENAR_POR_ARTISTA
        : PlaylistManager.ORDENAR_POR_NOMBRE;
 
    // Ejecutar QuickSort (lo validamos con un true)
    manager.quickSort(criterioOrden);
    estaOrdenado = true;
 
    // Mostrar estado DESPUÉS
    actualizarTabla(-1);
    String campo = (criterioOrden == PlaylistManager.ORDENAR_POR_ARTISTA) ? "Artista" : "Nombre";
    setStatus("Playlist ordenada por " + campo + " con QuickSort.", new Color(125, 211, 168));
 
    JOptionPane.showMessageDialog(this,
        "Ordenamiento completado.\nCriterio: " + campo +
        "\nEstado despues del ordenamiento:\n" + obtenerEstadoResumido(),
        "QuickSort finalizado", JOptionPane.INFORMATION_MESSAGE);   
    }//GEN-LAST:event_btnOrdenarActionPerformed

    //Metodo para buscar una cancion en la playlist usando búsqueda binaria
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     if (manager.estaVacia()) {
        setStatus("La playlist está vacia.", Color.YELLOW);
        return;
    }
    if (!estaOrdenado) {
        int resp = JOptionPane.showConfirmDialog(this,
            "El arreglo debe estar ordenado para la búsqueda binaria.\n¿Ordenar ahora por Nombre?",
            "Ordenar primero", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            manager.quickSort(PlaylistManager.ORDENAR_POR_NOMBRE);
            criterioOrden = PlaylistManager.ORDENAR_POR_NOMBRE;
            estaOrdenado = true;
            actualizarTabla(-1);
        } else return;
    }
 
    String[] opcionesBusqueda = {"Por Nombre", "Por Artista"};
    int tipoBusqueda = JOptionPane.showOptionDialog(this,
        "¿Buscar por?", "Tipo de busqueda",
        JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
        null, opcionesBusqueda, opcionesBusqueda[0]);
 
    if (tipoBusqueda == JOptionPane.CLOSED_OPTION) return;
 
    String termino = JOptionPane.showInputDialog(this,
        "Ingresa el " + opcionesBusqueda[tipoBusqueda] + " a buscar:");
    if (termino == null || termino.trim().isEmpty()) return;
 
    int indice = (tipoBusqueda == 1)
        ? manager.buscarPorArtista(termino.trim())
        : manager.buscarPorNombre(termino.trim());
 
    if (indice == -1) {
        actualizarTabla(-1);
        setStatus("No se encontro: \"" + termino + "\"", Color.RED);
        JOptionPane.showMessageDialog(this,
            "No se encontro ninguna cancion con: \"" + termino + "\"",
            "Busqueda", JOptionPane.WARNING_MESSAGE);
    } else {
        Cancion encontrada = manager.getCancion(indice);
        actualizarTabla(indice);
        setStatus("Encontrada en posición " + (indice + 1) + ": " + encontrada.nombre, new Color(125, 211, 168));
        JOptionPane.showMessageDialog(this,
            "Cancion encontrada!\n\n" +
            "Posicion : " + (indice + 1) + " de " + manager.getTamanio() + "\n" +
            "Nombre   : " + encontrada.nombre + "\n" +
            "Artista  : " + encontrada.artista + "\n" +
            "Album    : " + encontrada.album,
            "Resultado de busqueda", JOptionPane.INFORMATION_MESSAGE);
    }
   
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       if (manager.estaLleno()) {
        setStatus("⚠ La playlist está llena (máx. 50 canciones).", Color.YELLOW);
        return;
    }
 
    JTextField tfNombre  = new JTextField(20);
    JTextField tfArtista = new JTextField(20);
    JTextField tfAlbum   = new JTextField(20);
 
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
    panel.add(new JLabel("Nombre de la canción:"));  panel.add(tfNombre);
    panel.add(Box.createVerticalStrut(6));
    panel.add(new JLabel("Artista:"));               panel.add(tfArtista);
    panel.add(Box.createVerticalStrut(6));
    panel.add(new JLabel("Álbum (opcional):"));      panel.add(tfAlbum);
 
    int res = JOptionPane.showConfirmDialog(this, panel, "Agregar canción", JOptionPane.OK_CANCEL_OPTION);
    if (res != JOptionPane.OK_OPTION) return;
 
    String nombre  = tfNombre.getText().trim();
    String artista = tfArtista.getText().trim();
    if (nombre.isEmpty() || artista.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nombre y Artista son obligatorios.");
        return;
    }
 
    manager.agregar(nombre, artista, tfAlbum.getText().trim());
    estaOrdenado = false;
    actualizarTabla(-1);
    setStatus("✔ \"" + nombre + "\" agregada. Total: " + manager.getTamanio(), new Color(125, 211, 168));

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int resp = JOptionPane.showConfirmDialog(this,
        "¿Seguro que quieres salir?", "Salir", JOptionPane.YES_NO_OPTION);
    if (resp == JOptionPane.YES_OPTION) System.exit(0);
}
 
//Este es un resumen del arreglo para mostrar antes/despues
private String obtenerEstadoResumido() {
    Cancion[] canciones = manager.getPlaylist();
    StringBuilder sb = new StringBuilder();
    int mostrar = Math.min(canciones.length, 5);
    for (int i = 0; i < mostrar; i++) {
        sb.append("  ").append(i + 1).append(". ").append(canciones[i].nombre)
          .append(" — ").append(canciones[i].artista).append("\n");
    }
    if (canciones.length > 5) sb.append("  ... y ").append(canciones.length - 5).append(" más.");
    return sb.toString();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        btnMostrarActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         btnOrdenarActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   if (manager.estaVacia()) {
        setStatus("La playlist está vacia.", Color.YELLOW);
        return;
    }

    // Ordenar según el criterio seleccionado antes de buscar
    int criterio = jComboBox1.getSelectedIndex();
    if (!estaOrdenado || criterioOrden != criterio) {
        manager.quickSort(criterio);
        criterioOrden = criterio;
        estaOrdenado = true;
        actualizarTabla(-1);
    }

    String tipo = criterio == 0 ? "Nombre" : "Artista";
    String termino = JOptionPane.showInputDialog(this, "Ingresa el " + tipo + " a buscar:");
    if (termino == null || termino.trim().isEmpty()) return;

    int indice = criterio == 0
        ? manager.buscarPorNombre(termino.trim())
        : manager.buscarPorArtista(termino.trim());

    if (indice == -1) {
        actualizarTabla(-1);
        setStatus("No se encontro: \"" + termino + "\"", Color.RED);
    } else {
        Cancion encontrada = manager.getCancion(indice);
        actualizarTabla(indice);
        setStatus("Encontrada en posicion " + (indice + 1) + ": " + encontrada.nombre, new Color(125, 211, 168));
        JOptionPane.showMessageDialog(this,
            "Cancion encontrada!\n\n" +
            "Posicion : " + (indice + 1) + " de " + manager.getTamanio() + "\n" +
            "Nombre   : " + encontrada.nombre + "\n" +
            "Artista  : " + encontrada.artista + "\n" +
            "Album    : " + encontrada.album,
            "Resultado de busqueda", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
